### ISSUE TITLE
clean-base.py script fails trying to download built /vi

### ISSUE THREAD

**Issue by theVAX** [viur-framework/viur-base#14]
This is my console output:

Rolands-MacBook-Pro:projekt vax$ python clean-base.py
Enter Author Name (leave empty to default to vax): 
Enter application-id (leave empty to default to projekt-viur): mb-projekt-viur
Downloading submodules
Submodule 'deploy/server' (https://github.com/viur-framework/server.git) registered for path 'deploy/server'
Submodule 'sources/less/ignite' (https://github.com/viur-framework/ignite.git) registered for path 'sources/less/ignite'
Submodule 'vi' (https://github.com/viur-framework/vi.git) registered for path 'vi'
Cloning into '/Users/vax/Documents/Projects/projekt/deploy/server'...
Cloning into '/Users/vax/Documents/Projects/projekt/sources/less/ignite'...
Cloning into '/Users/vax/Documents/Projects/projekt/vi'...
Submodule 'html5' (https://github.com/viur-framework/html5.git) registered for path 'html5'
Submodule 'logics' (https://github.com/viur-framework/logics.git) registered for path 'logics'
Submodule 'public/icons' (https://github.com/viur-framework/icons.git) registered for path 'public/icons'
Cloning into '/Users/vax/Documents/Projects/projekt/vi/html5'...
Cloning into '/Users/vax/Documents/Projects/projekt/vi/logics'...
Cloning into '/Users/vax/Documents/Projects/projekt/vi/public/icons'...
Removing .git tether
.git remote tether removed
Downloading latest build of vi...Traceback (most recent call last):
  File "clean-base.py", line 101, in <module>
    urllib.urlretrieve("https://www.viur.is/package/download/vi/latest", zipname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

**Comment by phorward** [comment]
This is obsolete now with ViUR3.
