### ISSUE TITLE
Viur cant handle google-logging version provided in requirements.txt?

### ISSUE THREAD

**Issue by NicerDicer15** [viur-framework/viur-base#37]
My console output:

```python
Traceback (most recent call last):
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/workers/base.py", line 133, in init_process
    self.load_wsgi()
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/tmpAuLxhA/lib/python3.9/site-packages/gunicorn/util.py", line 331, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marco/Schreibtisch/projects/viur-test/deploy/main.py", line 26, in <module>
    from viur.core import conf, securityheaders
  File "/home/marco/Schreibtisch/projects/viur-test/deploy/viur/core/__init__.py", line 33, in <module>
    from viur.core import request
  File "/home/marco/Schreibtisch/projects/viur-test/deploy/viur/core/request.py", line 11, in <module>
    from viur.core.logging import requestLogger, client as loggingClient, requestLoggingRessource
  File "/home/marco/Schreibtisch/projects/viur-test/deploy/viur/core/logging.py", line 4, in <module>
    from google.cloud.logging.handlers.handlers import EXCLUDED_LOGGER_DEFAULTS
ModuleNotFoundError: No module named 'google.cloud.logging.handlers.handlers'
```

Seems to be fixed by downgrading the module from version 2.2.0 to 1.15.0

**Comment by sveneberth** [comment]
Hey, you're using an old version of the core. You have to update the submodule to at least https://github.com/viur-framework/viur-core/commit/8279922169bf41fbd8ccc4d46bd3d5350ec20842 to use logging v2.

**Comment by NicerDicer15** [comment]
Thank You! Everything is up-to-date and working now.
